apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insa-iot

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: insa-iot-api
  app.kubernetes.io/part-of: insa-iot-platform
  app.kubernetes.io/managed-by: kustomize

images:
- name: insa-iot/api
  newName: insa-iot/api
  newTag: latest
