apiVersion: v1
kind: Service
metadata:
  name: insa-iot-api-service
  namespace: insa-iot
  labels:
    app: insa-iot-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS
spec:
  type: ClusterIP
  selector:
    app: insa-iot-api
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: insa-iot-api-headless
  namespace: insa-iot
  labels:
    app: insa-iot-api
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: insa-iot-api
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
